apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-queue
  namespace: team43
spec:
  podSelector:
    matchLabels:
      app: redis-queue
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: todos-api
    ports:
    - protocol: TCP
      port: 6379
  - from:
    - podSelector:
        matchLabels:
          app: log-message-processor
    ports:
    - protocol: TCP
      port: 6379
