apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      restartPolicy: Always
      containers:
      - name: auth-api
        image: 561341012850.dkr.ecr.us-east-1.amazonaws.com/team43-auth-api:latest
        ports:
        - name: auth-api-port
          containerPort: 8081
          protocol: TCP
