apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      restartPolicy: Always
      containers:
      - name: frontend
        image: 561341012850.dkr.ecr.us-east-1.amazonaws.com/team43-frontend:latest
        ports:
        - name: frontend-port
          containerPort: 8080
          protocol: TCP
