apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend
  namespace: team43
spec:
  ingressClassName: nginx
  rules:
  - host: frontend.team43.k8s-ctf.com
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 8080
