apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor
  namespace: team43
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-message-processor
  template:
    metadata:
      labels:
        app: log-message-processor
        redis-access: "true"
    spec:
      restartPolicy: Always
      containers:
      - name: log-message-processor
        image: 561341012850.dkr.ecr.us-east-1.amazonaws.com/team43-log-message-processor:latest
        env:
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: log-message-processor
                key: REDIS_HOST
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: log-message-processor
                key: REDIS_PORT
          - name: REDIS_CHANNEL
            valueFrom:
              configMapKeyRef:
                name: log-message-processor
                key: REDIS_CHANNEL
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: log-message-processor
