apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      restartPolicy: Always
      containers:
      - name: users-api
        image: 561341012850.dkr.ecr.us-east-1.amazonaws.com/team43-users-api:latest
        ports:
        - name: users-api-port
          containerPort: 8083
          protocol: TCP
